---
  - name: Deploy Systems
    hosts: all
    become: true
    tasks:
      - name: Create ansiuser on worker nodes
        user:
          state: present
          shell: /bin/bash
          name: ansiuser
          password: "{{ 'ansiuser' | password_hash('sha512')}}"
          update_password: on_create
        when: ansible_hostname != "master"

      - name: Create ansiuser on master nodes
        user:
          state: present
          shell: /bin/bash
          name: ansiuser
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa
          force: yes
          password: "{{ 'ansiuser' | password_hash('sha512')}}"
          update_password: on_create
        when: ansible_hostname == "master"
      
      - name: sudo
        copy:
          dest: /etc/sudoers.d/ansiuser
          content: "ansiuser ALL=(ALL:ALL) NOPASSWD: ALL"

      - name: Add master and worker nodes to host file
        blockinfile:
          path: /etc/hosts
          block: |
            {{ item.ip }} {{ item.name }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
        loop:
          - {name: master, ip: 192.168.50.2 }
          - {name: worker1, ip: 192.168.50.3 }
          - {name: worker2, ip: 192.168.50.4 }

      - name: edit_sshd
        lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication yes'
          insertafter: '^PasswordAuthentication'
          state: present
        notify: restart_sshd
      
      - name: Add software-properties-common
        apt:
          name: software-properties-common
          state: present
          update-cache: yes
        when: ansible_hostname == "master"
          

      - name: add Ansible repository on master node
        ansible.builtin.apt_repository:
          repo: 'ppa:ansible/ansible'
        when: ansible_hostname == "master"
      
      - name: install {{ item }} on master node
        apt:
          name: "{{ item }}"
          state: present
          update-cache: yes
        with_items:
          - ansible
          - sshpass
        when: ansible_hostname == "master"

      - name: "Add worker nodes in ansible/hosts file"
        blockinfile:
          path: /etc/ansible/hosts
          block: |
            {{ item }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
        with_items:
          - worker1
          - worker2
        when: ansible_hostname == "master"

      - name: copy ssh key to worker nodes
        command: "sshpass -v -p ansiuser ssh-copy-id -o StrictHostKeyChecking=no ansiuser@{{ item }}"
        become_user: ansiuser
        with_items:
          - worker1
          - worker2
        when: ansible_hostname == "master"

    handlers:
      - name: restart_sshd
        service:
          name: sshd
          state: restarted
